### PR TITLE
Rebuild .selectors array on .remove()

### LINKED ISSUE #26: `remove` does not reduce size of `selectors`
Just stumbled upon this bug in selector-observer with jsdom ([related bug](https://github.com/jsdom/jsdom/issues/2680)).

The selector-observer case:
```js
const { JSDOM } = require("jsdom")
const {window} = new JSDOM(``, {});
const {document} = window

  import {observe} from 'selector-observer'

  let o1 = observe('.foo', {})
  o1.abort()
  let o2 = observe('.foo', {})
  o2.abort()
  let o3 = observe('.bar', {})
  o3.abort()
  await Promise.resolve().then()

  document.body.appendChild(document.createElement('div'))
```
This gives error in jsdom env:
```sh
Error: Uncaught [TypeError: Cannot read property '0' of undefined]
    at reportException (C:\projects\spect\node_modules\window\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:62:24)
    at notifyMutationObservers (C:\projects\spect\node_modules\window\node_modules\jsdom\lib\jsdom\living\helpers\mutation-observers.js:166:11)
    at C:\projects\spect\node_modules\window\node_modules\jsdom\lib\jsdom\living\helpers\mutation-observers.js:133:5
    at processTicksAndRejections (internal/process/task_queues.js:82:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:59:3)
    at C:\projects\spect\node_modules\esm\esm.js:1:34535
    at C:\projects\spect\node_modules\esm\esm.js:1:34176
    at process.<anonymous> (C:\projects\spect\node_modules\esm\esm.js:1:34506)
    at Function.<anonymous> (C:\projects\spect\node_modules\esm\esm.js:1:296856)
    at Function.<anonymous> (C:\projects\spect\node_modules\esm\esm.js:1:296555) TypeError: Cannot read property '0' of undefined
    at results_from (C:\projects\spect\node_modules\nwsapi\src\nwsapi.js:1522:48)
    at Object._querySelectorAll [as select] (C:\projects\spect\node_modules\nwsapi\src\nwsapi.js:1499:15)
    at HTMLDivElementImpl.querySelectorAll (C:\projects\spect\node_modules\window\node_modules\jsdom\lib\jsdom\living\nodes\ParentNode-impl.js:72:26)
    at HTMLDivElement.querySelectorAll (C:\projects\spect\node_modules\window\node_modules\jsdom\lib\jsdom\living\generated\Element.js:839:47)
    at SelectorSet._2e9‍.r.SelectorSet.querySelectorAll (C:\projects\spect\node_modules\selector-set\selector-set.next.js:53:18)
    at SelectorSet._2e9‍.r.SelectorSet.queryAll (C:\projects\spect\node_modules\selector-set\selector-set.next.js:346:18)
    at addNodes (C:\projects\spect\node_modules\selector-observer\dist\index.esm.js:343:51)
    at handleMutations$1 (C:\projects\spect\node_modules\selector-observer\dist\index.esm.js:310:7)
    at SelectorObserver.handleRootMutations (C:\projects\spect\node_modules\selector-observer\dist\index.esm.js:599:3)
    at notifyMutationObservers (C:\projects\spect\node_modules\window\node_modules\jsdom\lib\jsdom\living\helpers\mutation-observers.js:158:14)
```

Delving in debugging, `selector-observer` forms wrong selector even if it was aborted.
Turns out, `selector-set`, after calling `remove`, still keeps `set.selectors`:

```js
  var set = new SelectorSet();
  set.add('.foo')
  set.add('.foo')
  console.log(set.selectors) // ['.foo', '.foo']
  set.remove('.foo')
  console.log(set.selectors) // ['.foo', '.foo']
```

@josh is that by design?

### PR DESCRIPTION
**Pull request by josh**
Fixes #26.
Alternative and closes #27.

##

CC: @dy

### CODE REVIEW

File: selector-set.js [hunk 1]
```diff
@@ -342,7 +356,15 @@
       }
     }
 
-    this.size -= Object.keys(removedIds).length;
+    for (i in removedIds) {
+      delete selectorObjects[i];
+      this.size--;
+    }
+
+    this.selectors = selectors;
```
Comment (dy) [inline selector-set.js]: I'd just directly do it here - a bit less confusing.
```suggestion
    this.selectors = [];
```

File: selector-set.js [hunk 2]
```diff
@@ -310,10 +315,19 @@
...
+    var selectorIndexes,
+      selectorIndex,
+      i,
+      j,
+      k,
+      selIndex,
+      objs,
+      obj,
+      indexes = this.activeIndexes,
+      selectors = [],
```
Comment (dy) [inline selector-set.js]:
```suggestion
```

**Comment by josh** [comment]
> Just curious how would you generate `selector-set.next.js`

Manually 🤦🏻‍♂️
